services:
  extract_load:
    build:
      context: ..
      dockerfile: extract_load/Dockerfile
    container_name: extract_load
    networks:
      - dc_network
    environment:
      DB_HOST: postgres_sv
      DB_NAME: pg_database
      DB_USER: main_user
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - ./logs:/logs

networks:
  dc_network:
    name: dc_network
    external: true

secrets:
  db_password:
    file: ../secrets/postgres_password.txt