services:
  query:
    build:
      context: ..
      dockerfile: query/Dockerfile
    container_name: query
    networks:
      - dc_network
    environment:
      DB_HOST: postgres_sv
      DB_NAME: pg_database
      DB_USER: main_user
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password

networks:
  dc_network:
    name: dc_network
    external: true

secrets:
  db_password:
    file: ../secrets/postgres_password.txt